# -*- mode:python -*-

# Copyright (c) 2006 The Regents of The University of Michigan
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Authors: Nathan Binkert

import sys

Import('*')


if 'O3liteCPU' in env['CPU_MODELS']:
    SimObject('O3liteFUPool.py')
    SimObject('O3liteFuncUnitConfig.py')
    SimObject('O3liteCPU.py')

    Source('base_dyn_inst.cc')
    Source('bpred_unit.cc')
    Source('commit.cc')
    Source('cpu.cc')
    Source('cpu_builder.cc')
    Source('decode.cc')
    Source('dyn_inst.cc')
    Source('fetch.cc')
    Source('free_list.cc')
    Source('fu_pool.cc')
    Source('iew.cc')
    Source('inst_queue.cc')
    Source('lsq.cc')
    Source('lsq_unit.cc')
    Source('mem_dep_unit.cc')



    Source('rename.cc')
    Source('rename_map.cc')
    Source('rob.cc')
    Source('scoreboard.cc')
    Source('store_set.cc')
    Source('thread_context.cc')

if 'O3CPU' not in env['CPU_MODELS']: 
    TraceFlag('CommitRate')
    TraceFlag('IEW')
    TraceFlag('IQ')
    TraceFlag('LSQ')
    TraceFlag('LSQUnit')
    TraceFlag('MemDepUnit')
    TraceFlag('O3CPU')
    TraceFlag('ROB')
    TraceFlag('Rename')
    TraceFlag('Scoreboard')
    TraceFlag('StoreSet')
    TraceFlag('Writeback')

    CompoundFlag('CPUAll', [ 'Fetch', 'Decode', 'Rename', 'IEW', 'Commit',
        'IQ', 'ROB', 'FreeList', 'LSQ', 'LSQUnit', 'StoreSet', 'MemDepUnit',
        'DynInst', 'O3CPU', 'Activity', 'Scoreboard', 'Writeback' ])

#    TraceFlag('O3liteCommitRate')
#    TraceFlag('O3liteIEW')
#    TraceFlag('O3liteIQ')
#    TraceFlag('O3liteLSQ')
#    TraceFlag('O3liteLSQUnit')
#    TraceFlag('O3liteMemDepUnit')
#    TraceFlag('O3liteO3CPU')
#    TraceFlag('O3liteROB')
#    TraceFlag('O3liteRename')
#    TraceFlag('O3liteScoreboard')
#    TraceFlag('O3liteStoreSet')
#    TraceFlag('O3liteWriteback')
#
#    CompoundFlag('O3liteCPUAll', [ 'O3liteFetch', 'O3liteDecode', 'O3liteRename', 'O3liteIEW', 'O3liteCommit',
#        'O3liteIQ', 'O3liteROB', 'O3liteFreeList', 'O3liteLSQ', 'O3liteLSQUnit', 'O3liteStoreSet', 'O3liteMemDepUnit',
#        'O3liteDynInst', 'O3liteCPU', 'O3liteActivity', 'O3liteScoreboard', 'O3liteWriteback' ])
